### ISSUE TITLE
Inconsistent use of uint_16_t and Handle_t

### ISSUE THREAD

**Issue by aleksanb** [mbedmicro/BLE_API#34]
Hey.
[getHandle](https://github.com/mbedmicro/BLE_API/blob/master/public/GattAttribute.h#L54) returns a Handle_t, but [updateCharacteristicValue](https://github.com/mbedmicro/BLE_API/blob/master/public/BLEDevice.h#L278) expects an uint_16_t.

This was rather confusing, until i discovered that Handle_t was a typedef of uint_16_t.

May i suggest returning a uint_16_t from updateCharacteristicValue instead, as the discrepancy feels somewhat confusing?

**Comment by rgrover** [comment]
yup. This was on my todo list. Thanks for pointing this out. Fix should arrive shortly.
