### ISSUE TITLE
BLEDevice::clearAdvertisingPayload doesn't clear the scan response PDU

### ISSUE THREAD

**Issue by kellyjp** [mbedmicro/BLE_API#36]
There appears to be no way to clear the scan response stored in BLEDevice::scanResponse in the current API.  The logical place for this is probably in clearAdvertisingPayload method as the scanResponse is just an extension of the advertising payload.  However, if you don't want to change the semantics of the current API another method could be added to the API to do this i.e. clearScanResponse.

**Comment by rgrover** [comment]
Thanks for raising this. I'll investigate if this is possible.
