### ISSUE TITLE
Initial value for _requiredSecurity member of GattCharacteristic class breaks existing code

### ISSUE THREAD

**Issue by kellyjp** [mbedmicro/BLE_API#39]
The constructor for GattCharacteristic implicitly initialises the value of the _requiredSecurity member to Gap::SECURITY_MODE_NO_ACCESS (0).  Read requests for any characteristic will therefore fail unless there is a call to the requireSecurity method to change it to something more permissive.

As a consequence all existing code that supports reads of a characteristic value will now return an error to the client whenever the client attempts to read the characteristic value.

This breakage could be fixed by explicitly setting the value of the _requiredSecurity member to Gap::SECURITY_MODE_ENCRYPTION_OPEN_LINK in the constructor for GattCharacteristic.  If more restrictive access is desired, new code that is aware of the new security features of the API can request this with a call to the requireSecurity method.

**Comment by rgrover** [comment]
Thanks for this excellent root-cause analysis. This will be fixed very shortly.
