### ISSUE TITLE
Typo in definition of UNIT_0_625_MS in Gap.h

### ISSUE THREAD

**Issue by kellyjp** [mbedmicro/BLE_API#40]
This constant is currently defined as 650 when it should be defined as 625.  I discovered this typo when attempting to set the advertising interval to 20ms (the minimum allowable value) and it was failing.  With the typo corrected setting the advertising interval to 20ms now works.

**Comment by rgrover** [comment]
Yes, I had already noticed this. The fix will come with the next release. Thanks so much for your feedback.

**Comment by rgrover** [comment]
It may take a day for mbed.org to get updated with this change because we're waiting for the new mbed-SDK to be rolled out.
