### ISSUE TITLE
Need some help regarding the development of BLE network simulator

### ISSUE THREAD

**Issue by praveenpnj94** [mbedmicro/BLE_API#52]
Hi Mr. Rohit,
@rgrover 

I am really sorry for this as my post may sound unclear and weird but i am in need of some help. I was trying to develop a network simulator for BLE network so that we can simulate and check where to place the beacons depending upon the mobility pattern, varying different scan and advertising intervals. For this, we were trying to use NS3 and build BLE module. But BLE seems a lot complex. 

But later i checked your BLE API and tried to build it in eclipse after importing from GitHub. But there occurs nothing. It is not getting built. So, how to build it? Kindly help me and show some guidelines. Also only header files have been declared. How will be the message passing process will be accompanied here. How to include the source files and add the mechanism here?

Any help will be appreciated.

Thanks

**Comment by rgrover** [comment]
please refer to: http://docs.mbed.org/docs/ble-intros/en/latest/GettingStarted/IntroSamples/
